### ISSUE TITLE
Segfaults on 0.4?

### ISSUE THREAD

**Issue by tkelman** [JuliaOpt/GLPK.jl#21]
Looks like this happened on PkgEvaluator, it doesn't happen every time for me and might be a base Julia gc issue, not sure.

```
tkelman@ygdesk:~/Julia/julia$ gdb --args usr/bin/julia-debug --check-bounds=yes -e 'include(Pkg.dir("GLPK","test","runtests.jl"))'
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from usr/bin/julia-debug...done.
(gdb) r
Starting program: /home/tkelman/Julia/julia/usr/bin/julia-debug --check-bounds=yes -e include\(Pkg.dir\(\"GLPK\",\"test\",\"runtests.jl\"\)\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffdf05d7700 (LWP 29398)]
Running glpk_tst_1.jl
WARNING: dlopen_e is deprecated, use Libdl.dlopen_e instead.
 in depwarn at ./deprecated.jl:40
 in dlopen_e at deprecated.jl:10
 in anonymous at /home/tkelman/.julia/v0.4/GLPK/src/../deps/deps.jl:7
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in anonymous at no file:19
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in process_options at ./client.jl:291
 in _start at ./client.jl:401
WARNING: parseint(s) is deprecated, use parse(Int,s) instead.
 in depwarn at ./deprecated.jl:40
 in parseint at deprecated.jl:29
 in anonymous at /home/tkelman/.julia/v0.4/GLPK/src/GLPK.jl:236
 in map at ./abstractarray.jl:1317
 in version at /home/tkelman/.julia/v0.4/GLPK/src/GLPK.jl:236
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in reload_path at ./loading.jl:153
 in _require at ./loading.jl:68
 in require at ./loading.jl:51
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in anonymous at no file:19
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in process_options at ./client.jl:291
 in _start at ./client.jl:401

WARNING: deprecated syntax "(Uint=>Bool)[]" at /home/tkelman/.julia/v0.4/GLPK/src/GLPK_checks.jl:19.
Use "Dict{Uint,Bool}()" instead.
Running glpk_tst_2.jl
Running glpk_tst_3.jl
Running glpk_tst_4.jl
WARNING: int(x) is deprecated, use Int(x) instead.
 in depwarn at ./deprecated.jl:40
 in int at deprecated.jl:29
 in glpk_tst_4 at /home/tkelman/.julia/v0.4/GLPK/test/glpk_tst_4.jl:62
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in anonymous at no file:19
 in include at ./boot.jl:250
 in include_from_node1 at ./loading.jl:129
 in process_options at ./client.jl:291
 in _start at ./client.jl:401

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6e7b189 in push_root (v=0x7fffffffb4d0, d=2, bits=3) at gc.c:1583
1583            int nf = (int)jl_tuple_len(dt->names);
(gdb) bt
#0  0x00007ffff6e7b189 in push_root (v=0x7fffffffb4d0, d=2, bits=3) at gc.c:1583
#1  0x00007ffff6e7a553 in gc_push_root (v=0x7fffffffb4d0, d=1) at gc.c:1319
#2  0x00007ffff6e7a67c in gc_mark_stack (ta=0x7ffdf3140010, s=0x7fffffffb450, offset=0, d=1)
    at gc.c:1349
#3  0x00007ffff6e7a94d in gc_mark_task_stack (ta=0x7ffdf3140010, d=1) at gc.c:1410
#4  0x00007ffff6e7aabf in gc_mark_task (ta=0x7ffdf3140010, d=1) at gc.c:1440
#5  0x00007ffff6e7b0cf in push_root (v=0x7ffdf3140010, d=1, bits=1) at gc.c:1560
#6  0x00007ffff6e7be18 in jl_gc_collect (full=0) at gc.c:2036
#7  0x00007ffff6e79419 in __pool_alloc (p=0x7ffff7daf370 <norm_pools+144>, osize=32,
    end_offset=16352) at gc.c:927
#8  0x00007ffff6e79652 in _pool_alloc (p=0x7ffff7daf370 <norm_pools+144>, osize=32) at gc.c:974
#9  0x00007ffff6e7c634 in alloc_2w () at gc.c:2280
#10 0x00007ffff6e56052 in newobj (type=0x7ffdf3100010, nfields=2) at julia_internal.h:18
#11 0x00007ffff6e576b1 in jl_alloc_tuple_uninit (n=1) at alloc.c:389
#12 0x00007ffff6e57715 in jl_alloc_tuple (n=1) at alloc.c:398
#13 0x00007ffff6ddd48c in jl_cfunction_object (f=0x7ffdf5121708, rt=0x7ffdf30fc240,
    argt=0x7ffdf54226d0) at codegen.cpp:801
#14 0x00007ffff6ddd80c in jl_function_ptr (f=0x7ffdf5121708, rt=0x7ffdf30fc240,
    argt=0x7ffdf54226d0) at codegen.cpp:860
#15 0x00007ffff7ed1393 in ?? ()
#16 0xb67b215477b7c900 in ?? ()
#17 0x0000000000000002 in ?? ()
#18 0x00007fffffffb548 in ?? ()
#19 0x00007ffdf54226d0 in ?? ()
#20 0xb67b215477b7c900 in ?? ()
#21 0x0000000000000288 in ?? ()
#22 0x00007ffff7e74450 in ?? ()
#23 0x00007ffdf5b84dc0 in ?? ()
#24 0x00007fffffffb5a0 in ?? ()
#25 0x00007ffff7ed5947 in ?? ()
#26 0x00007fffffffbaf8 in ?? ()
#27 0x00007ffdf5b84dc0 in ?? ()
#28 0x000000000000024a in ?? ()
#29 0x0000000000000006 in ?? ()
#30 0x00007fffffffb9f8 in ?? ()
#31 0x0000000000000000 in ?? ()
(gdb) q
A debugging session is active.

        Inferior 1 [process 29394] will be killed.

Quit anyway? (y or n) y
tkelman@ygdesk:~/Julia/julia$ ./julia -e 'versioninfo()'
Julia Version 0.4.0-dev+4128
Commit 9b0d15b* (2015-04-01 21:47 UTC)
DEBUG build
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT NO_AFFINITY PENRYN)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by mlubin** [comment]
Yep, reported at JuliaLang/julia#10600

**Comment by tkelman** [comment]
Ah, sorry for the dupe. May as well close this then.
